name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Dependencies
        run: |
          sudo apt install -y nasm gcc g++ golang openjdk-17-jdk python3 rustc curl
          cd ~; curl https://ziglang.org/download/0.13.0/zig-linux-x86_64-0.13.0.tar.xz -o zig-linux-x86_64-0.13.0.tar.xz; tar -xf zig-linux-x86_64-0.13.0.tar.xz; export PATH=$PATH:~/zig-linux-x86_64-0.13.0; cd -

      - name: Make
        run: make

      - name: Make tests
        run: make tests
